export const BookingConstants = {
  MAX_SESSION_HOURS: 8,
  DEFAULT_COMMISSION_RATE: 0.18,
  DISPUTE_WINDOW_HOURS: 48,
  AUTO_COMPLETE_GRACE_PERIOD_HOURS: 2,
  MAX_COMPLETION_GRACE_HOURS: 168,

  CONFIRMATION_REMINDER_INTERVALS_HOURS: [6, 12, 24] as const,
  CONFIRMATION_REMINDER_SEARCH_WINDOW_HOURS: 1,

  STALE_SESSION_THRESHOLD_HOURS: 6,

  MISSING_MEETING_LINK_WINDOW_MINUTES_START: 20,
  MISSING_MEETING_LINK_WINDOW_MINUTES_END: 30,

  MEETING_LINK_REMINDER_WINDOW_MINUTES_START: 20,
  MEETING_LINK_REMINDER_WINDOW_MINUTES_END: 40,

  SESSION_START_REMINDER_WINDOW_MINUTES_START: 50,
  SESSION_START_REMINDER_WINDOW_MINUTES_END: 60,
} as const;
